// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"encoding/json"
	"fmt"
	"github.com/speakeasy-sdks/naumanali/pkg/models/shared"
	"net/http"
)

type ExportFileByBranchSecurity struct {
	Authorization string `security:"scheme,type=http,subtype=bearer,name=Authorization"`
}

func (o *ExportFileByBranchSecurity) GetAuthorization() string {
	if o == nil {
		return ""
	}
	return o.Authorization
}

// ExportFileByBranchStoplightVersionStoplightAPIVersionString - A string representing the Stoplight API version that is being requested. If not supplied: TODO document policy
type ExportFileByBranchStoplightVersionStoplightAPIVersionString string

const (
	ExportFileByBranchStoplightVersionStoplightAPIVersionStringTwoThousandAndTwentyTwo1205 ExportFileByBranchStoplightVersionStoplightAPIVersionString = "2022-12-05"
)

func (e ExportFileByBranchStoplightVersionStoplightAPIVersionString) ToPointer() *ExportFileByBranchStoplightVersionStoplightAPIVersionString {
	return &e
}

func (e *ExportFileByBranchStoplightVersionStoplightAPIVersionString) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "2022-12-05":
		*e = ExportFileByBranchStoplightVersionStoplightAPIVersionString(v)
		return nil
	default:
		return fmt.Errorf("invalid value for ExportFileByBranchStoplightVersionStoplightAPIVersionString: %v", v)
	}
}

type ExportFileByBranchRequest struct {
	// A string representing the Stoplight API version that is being requested. If not supplied: TODO document policy
	StoplightVersion *ExportFileByBranchStoplightVersionStoplightAPIVersionString `header:"style=simple,explode=false,name=Stoplight-Version"`
	// A reference to a branch tracked by a Stoplight project. Must be percent encoded.
	BranchName string `pathParam:"style=simple,explode=false,name=branch_name"`
	// A path to a file in a Stoplight project. Use forward slashes (`/`) to separate path directories.
	FilePath string `pathParam:"style=simple,explode=false,name=file_path"`
	// When `false`, indicates that any declaration (schema, operation, property, etc.) in the OpenAPI or JSON Schema marked with the `x-internal` extension property set to `true` will be omitted from the exported file. Setting this parameter to `true` with an anonymous or workspace guest user caller results in an error response.
	IncludeInternal *bool `queryParam:"style=form,explode=true,name=include_internal"`
	// A string that uniquely identifies a Stoplight Project resource. This can be found in the [Project Settings](https://docs.stoplight.io/docs/platform/252039ebe8fb2-project-settings) page.
	ProjectID string `pathParam:"style=simple,explode=false,name=project_id"`
}

func (o *ExportFileByBranchRequest) GetStoplightVersion() *ExportFileByBranchStoplightVersionStoplightAPIVersionString {
	if o == nil {
		return nil
	}
	return o.StoplightVersion
}

func (o *ExportFileByBranchRequest) GetBranchName() string {
	if o == nil {
		return ""
	}
	return o.BranchName
}

func (o *ExportFileByBranchRequest) GetFilePath() string {
	if o == nil {
		return ""
	}
	return o.FilePath
}

func (o *ExportFileByBranchRequest) GetIncludeInternal() *bool {
	if o == nil {
		return nil
	}
	return o.IncludeInternal
}

func (o *ExportFileByBranchRequest) GetProjectID() string {
	if o == nil {
		return ""
	}
	return o.ProjectID
}

type ExportFileByBranchResponse struct {
	// The server could not understand the request due to invalid syntax.
	BadRequestProblemDetail *shared.BadRequestProblemDetail
	Body                    []byte
	// This response is sent when a request conflicts with the current state of the server.
	ConflictProblemDetail *shared.ConflictProblemDetail
	ContentType           string
	// The server could not export the file contents requested.
	ExportFileFailedProblemDetail *shared.ExportFileFailedProblemDetail
	// The client does not have permissions to access the content.
	ForbiddenProblemDetail *shared.ForbiddenProblemDetail
	Headers                map[string][]string
	// The server has encountered a situation it doesn't know how to handle.
	InternalServerErrorProblemDetail *shared.InternalServerErrorProblemDetail
	// The server can not find the requested resource.
	NotFoundProblemDetail *shared.NotFoundProblemDetail
	// The client needs to provide payment to access the request content.
	PaymentRequiredProblemDetail *shared.PaymentRequiredProblemDetail
	StatusCode                   int
	RawResponse                  *http.Response
	// This response is sent when the client has exhausted the request quota.
	TooManyRequestsProblemDetail *shared.TooManyRequestsProblemDetail
	// The client must authenticate itself to get the requested response.
	UnauthorizedProblemDetail *shared.UnauthorizedProblemDetail
	// The exported OpenAPI or JSON Schema file.
	ExportFileByBranch200ApplicationJSONAny interface{}
}

func (o *ExportFileByBranchResponse) GetBadRequestProblemDetail() *shared.BadRequestProblemDetail {
	if o == nil {
		return nil
	}
	return o.BadRequestProblemDetail
}

func (o *ExportFileByBranchResponse) GetBody() []byte {
	if o == nil {
		return nil
	}
	return o.Body
}

func (o *ExportFileByBranchResponse) GetConflictProblemDetail() *shared.ConflictProblemDetail {
	if o == nil {
		return nil
	}
	return o.ConflictProblemDetail
}

func (o *ExportFileByBranchResponse) GetContentType() string {
	if o == nil {
		return ""
	}
	return o.ContentType
}

func (o *ExportFileByBranchResponse) GetExportFileFailedProblemDetail() *shared.ExportFileFailedProblemDetail {
	if o == nil {
		return nil
	}
	return o.ExportFileFailedProblemDetail
}

func (o *ExportFileByBranchResponse) GetForbiddenProblemDetail() *shared.ForbiddenProblemDetail {
	if o == nil {
		return nil
	}
	return o.ForbiddenProblemDetail
}

func (o *ExportFileByBranchResponse) GetHeaders() map[string][]string {
	if o == nil {
		return nil
	}
	return o.Headers
}

func (o *ExportFileByBranchResponse) GetInternalServerErrorProblemDetail() *shared.InternalServerErrorProblemDetail {
	if o == nil {
		return nil
	}
	return o.InternalServerErrorProblemDetail
}

func (o *ExportFileByBranchResponse) GetNotFoundProblemDetail() *shared.NotFoundProblemDetail {
	if o == nil {
		return nil
	}
	return o.NotFoundProblemDetail
}

func (o *ExportFileByBranchResponse) GetPaymentRequiredProblemDetail() *shared.PaymentRequiredProblemDetail {
	if o == nil {
		return nil
	}
	return o.PaymentRequiredProblemDetail
}

func (o *ExportFileByBranchResponse) GetStatusCode() int {
	if o == nil {
		return 0
	}
	return o.StatusCode
}

func (o *ExportFileByBranchResponse) GetRawResponse() *http.Response {
	if o == nil {
		return nil
	}
	return o.RawResponse
}

func (o *ExportFileByBranchResponse) GetTooManyRequestsProblemDetail() *shared.TooManyRequestsProblemDetail {
	if o == nil {
		return nil
	}
	return o.TooManyRequestsProblemDetail
}

func (o *ExportFileByBranchResponse) GetUnauthorizedProblemDetail() *shared.UnauthorizedProblemDetail {
	if o == nil {
		return nil
	}
	return o.UnauthorizedProblemDetail
}

func (o *ExportFileByBranchResponse) GetExportFileByBranch200ApplicationJSONAny() interface{} {
	if o == nil {
		return nil
	}
	return o.ExportFileByBranch200ApplicationJSONAny
}
