// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package sdkerrors

// ExportProblem - Problems encountered while exporting content
type ExportProblem struct {
	// detailed message about the error
	Detail string `json:"detail"`
	// The JSON Path where the error occurred
	Path string `json:"path"`
}

func (o *ExportProblem) GetDetail() string {
	if o == nil {
		return ""
	}
	return o.Detail
}

func (o *ExportProblem) GetPath() string {
	if o == nil {
		return ""
	}
	return o.Path
}
