// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

import (
	"encoding/json"
	"fmt"
)

// ConflictProblemDetailProblemDetailStatus - The HTTP status code generated by the origin server for this occurrence of the problem.
type ConflictProblemDetailProblemDetailStatus int64

const (
	ConflictProblemDetailProblemDetailStatusFourHundred              ConflictProblemDetailProblemDetailStatus = 400
	ConflictProblemDetailProblemDetailStatusFourHundredAndOne        ConflictProblemDetailProblemDetailStatus = 401
	ConflictProblemDetailProblemDetailStatusFourHundredAndTwo        ConflictProblemDetailProblemDetailStatus = 402
	ConflictProblemDetailProblemDetailStatusFourHundredAndThree      ConflictProblemDetailProblemDetailStatus = 403
	ConflictProblemDetailProblemDetailStatusFourHundredAndFour       ConflictProblemDetailProblemDetailStatus = 404
	ConflictProblemDetailProblemDetailStatusFourHundredAndNine       ConflictProblemDetailProblemDetailStatus = 409
	ConflictProblemDetailProblemDetailStatusFourHundredAndTwentyNine ConflictProblemDetailProblemDetailStatus = 429
	ConflictProblemDetailProblemDetailStatusFiveHundred              ConflictProblemDetailProblemDetailStatus = 500
)

func (e ConflictProblemDetailProblemDetailStatus) ToPointer() *ConflictProblemDetailProblemDetailStatus {
	return &e
}

func (e *ConflictProblemDetailProblemDetailStatus) UnmarshalJSON(data []byte) error {
	var v int64
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case 400:
		fallthrough
	case 401:
		fallthrough
	case 402:
		fallthrough
	case 403:
		fallthrough
	case 404:
		fallthrough
	case 409:
		fallthrough
	case 429:
		fallthrough
	case 500:
		*e = ConflictProblemDetailProblemDetailStatus(v)
		return nil
	default:
		return fmt.Errorf("invalid value for ConflictProblemDetailProblemDetailStatus: %v", v)
	}
}

// ConflictProblemDetail - Represents when a request conflicts with the current state of the server.
type ConflictProblemDetail struct {
	// A human-readable explanation specific to this occurrence of the problem.
	Detail *string `json:"detail,omitempty"`
	// A URI reference that identifies the specific occurrence of the problem.
	Instance *string                                  `json:"instance,omitempty"`
	Status   ConflictProblemDetailProblemDetailStatus `json:"status"`
	// A short, human-readable summary of the problem type.
	Title string `json:"title"`
	// A URI reference that identifies the problem type.
	Type string `json:"type"`
}

func (o *ConflictProblemDetail) GetDetail() *string {
	if o == nil {
		return nil
	}
	return o.Detail
}

func (o *ConflictProblemDetail) GetInstance() *string {
	if o == nil {
		return nil
	}
	return o.Instance
}

func (o *ConflictProblemDetail) GetStatus() ConflictProblemDetailProblemDetailStatus {
	if o == nil {
		return ConflictProblemDetailProblemDetailStatus(0)
	}
	return o.Status
}

func (o *ConflictProblemDetail) GetTitle() string {
	if o == nil {
		return ""
	}
	return o.Title
}

func (o *ConflictProblemDetail) GetType() string {
	if o == nil {
		return ""
	}
	return o.Type
}
