// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

import (
	"encoding/json"
	"fmt"
)

// ForbiddenProblemDetailProblemDetailStatus - The HTTP status code generated by the origin server for this occurrence of the problem.
type ForbiddenProblemDetailProblemDetailStatus int64

const (
	ForbiddenProblemDetailProblemDetailStatusFourHundred              ForbiddenProblemDetailProblemDetailStatus = 400
	ForbiddenProblemDetailProblemDetailStatusFourHundredAndOne        ForbiddenProblemDetailProblemDetailStatus = 401
	ForbiddenProblemDetailProblemDetailStatusFourHundredAndTwo        ForbiddenProblemDetailProblemDetailStatus = 402
	ForbiddenProblemDetailProblemDetailStatusFourHundredAndThree      ForbiddenProblemDetailProblemDetailStatus = 403
	ForbiddenProblemDetailProblemDetailStatusFourHundredAndFour       ForbiddenProblemDetailProblemDetailStatus = 404
	ForbiddenProblemDetailProblemDetailStatusFourHundredAndNine       ForbiddenProblemDetailProblemDetailStatus = 409
	ForbiddenProblemDetailProblemDetailStatusFourHundredAndTwentyNine ForbiddenProblemDetailProblemDetailStatus = 429
	ForbiddenProblemDetailProblemDetailStatusFiveHundred              ForbiddenProblemDetailProblemDetailStatus = 500
)

func (e ForbiddenProblemDetailProblemDetailStatus) ToPointer() *ForbiddenProblemDetailProblemDetailStatus {
	return &e
}

func (e *ForbiddenProblemDetailProblemDetailStatus) UnmarshalJSON(data []byte) error {
	var v int64
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case 400:
		fallthrough
	case 401:
		fallthrough
	case 402:
		fallthrough
	case 403:
		fallthrough
	case 404:
		fallthrough
	case 409:
		fallthrough
	case 429:
		fallthrough
	case 500:
		*e = ForbiddenProblemDetailProblemDetailStatus(v)
		return nil
	default:
		return fmt.Errorf("invalid value for ForbiddenProblemDetailProblemDetailStatus: %v", v)
	}
}

// ForbiddenProblemDetail - Represents when the client does not have permissions to access the resource.
type ForbiddenProblemDetail struct {
	// A human-readable explanation specific to this occurrence of the problem.
	Detail *string `json:"detail,omitempty"`
	// A URI reference that identifies the specific occurrence of the problem.
	Instance *string                                   `json:"instance,omitempty"`
	Status   ForbiddenProblemDetailProblemDetailStatus `json:"status"`
	// A short, human-readable summary of the problem type.
	Title string `json:"title"`
	// A URI reference that identifies the problem type.
	Type string `json:"type"`
}

func (o *ForbiddenProblemDetail) GetDetail() *string {
	if o == nil {
		return nil
	}
	return o.Detail
}

func (o *ForbiddenProblemDetail) GetInstance() *string {
	if o == nil {
		return nil
	}
	return o.Instance
}

func (o *ForbiddenProblemDetail) GetStatus() ForbiddenProblemDetailProblemDetailStatus {
	if o == nil {
		return ForbiddenProblemDetailProblemDetailStatus(0)
	}
	return o.Status
}

func (o *ForbiddenProblemDetail) GetTitle() string {
	if o == nil {
		return ""
	}
	return o.Title
}

func (o *ForbiddenProblemDetail) GetType() string {
	if o == nil {
		return ""
	}
	return o.Type
}
