// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

import (
	"encoding/json"
	"fmt"
)

// InternalServerErrorProblemDetailProblemDetailStatus - The HTTP status code generated by the origin server for this occurrence of the problem.
type InternalServerErrorProblemDetailProblemDetailStatus int64

const (
	InternalServerErrorProblemDetailProblemDetailStatusFourHundred              InternalServerErrorProblemDetailProblemDetailStatus = 400
	InternalServerErrorProblemDetailProblemDetailStatusFourHundredAndOne        InternalServerErrorProblemDetailProblemDetailStatus = 401
	InternalServerErrorProblemDetailProblemDetailStatusFourHundredAndTwo        InternalServerErrorProblemDetailProblemDetailStatus = 402
	InternalServerErrorProblemDetailProblemDetailStatusFourHundredAndThree      InternalServerErrorProblemDetailProblemDetailStatus = 403
	InternalServerErrorProblemDetailProblemDetailStatusFourHundredAndFour       InternalServerErrorProblemDetailProblemDetailStatus = 404
	InternalServerErrorProblemDetailProblemDetailStatusFourHundredAndNine       InternalServerErrorProblemDetailProblemDetailStatus = 409
	InternalServerErrorProblemDetailProblemDetailStatusFourHundredAndTwentyNine InternalServerErrorProblemDetailProblemDetailStatus = 429
	InternalServerErrorProblemDetailProblemDetailStatusFiveHundred              InternalServerErrorProblemDetailProblemDetailStatus = 500
)

func (e InternalServerErrorProblemDetailProblemDetailStatus) ToPointer() *InternalServerErrorProblemDetailProblemDetailStatus {
	return &e
}

func (e *InternalServerErrorProblemDetailProblemDetailStatus) UnmarshalJSON(data []byte) error {
	var v int64
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case 400:
		fallthrough
	case 401:
		fallthrough
	case 402:
		fallthrough
	case 403:
		fallthrough
	case 404:
		fallthrough
	case 409:
		fallthrough
	case 429:
		fallthrough
	case 500:
		*e = InternalServerErrorProblemDetailProblemDetailStatus(v)
		return nil
	default:
		return fmt.Errorf("invalid value for InternalServerErrorProblemDetailProblemDetailStatus: %v", v)
	}
}

// InternalServerErrorProblemDetail - Represents when the server has encountered a situation it doesn't know how to handle.
type InternalServerErrorProblemDetail struct {
	// A human-readable explanation specific to this occurrence of the problem.
	Detail *string `json:"detail,omitempty"`
	// A URI reference that identifies the specific occurrence of the problem.
	Instance *string                                             `json:"instance,omitempty"`
	Status   InternalServerErrorProblemDetailProblemDetailStatus `json:"status"`
	// A short, human-readable summary of the problem type.
	Title string `json:"title"`
	// A URI reference that identifies the problem type.
	Type string `json:"type"`
}

func (o *InternalServerErrorProblemDetail) GetDetail() *string {
	if o == nil {
		return nil
	}
	return o.Detail
}

func (o *InternalServerErrorProblemDetail) GetInstance() *string {
	if o == nil {
		return nil
	}
	return o.Instance
}

func (o *InternalServerErrorProblemDetail) GetStatus() InternalServerErrorProblemDetailProblemDetailStatus {
	if o == nil {
		return InternalServerErrorProblemDetailProblemDetailStatus(0)
	}
	return o.Status
}

func (o *InternalServerErrorProblemDetail) GetTitle() string {
	if o == nil {
		return ""
	}
	return o.Title
}

func (o *InternalServerErrorProblemDetail) GetType() string {
	if o == nil {
		return ""
	}
	return o.Type
}
