// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

import (
	"encoding/json"
	"fmt"
)

// InvalidParameterIn - The location of the invalid parameter
type InvalidParameterIn string

const (
	InvalidParameterInBody   InvalidParameterIn = "body"
	InvalidParameterInHeader InvalidParameterIn = "header"
	InvalidParameterInPath   InvalidParameterIn = "path"
	InvalidParameterInQuery  InvalidParameterIn = "query"
)

func (e InvalidParameterIn) ToPointer() *InvalidParameterIn {
	return &e
}

func (e *InvalidParameterIn) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "body":
		fallthrough
	case "header":
		fallthrough
	case "path":
		fallthrough
	case "query":
		*e = InvalidParameterIn(v)
		return nil
	default:
		return fmt.Errorf("invalid value for InvalidParameterIn: %v", v)
	}
}

// InvalidParameter - Details why a certain parameter is invalid.
type InvalidParameter struct {
	// A human-readable explanation.
	Detail *string            `json:"detail,omitempty"`
	In     InvalidParameterIn `json:"in"`
	// The name of the invalid parameter
	Name *string `json:"name,omitempty"`
	// The JSON Path in the schema that the invalid parameter violated
	Path *string `json:"path,omitempty"`
	// The reason this parameter is invalid
	Title string `json:"title"`
	// A URI reference that identifies the problem type.
	Type string `json:"type"`
}

func (o *InvalidParameter) GetDetail() *string {
	if o == nil {
		return nil
	}
	return o.Detail
}

func (o *InvalidParameter) GetIn() InvalidParameterIn {
	if o == nil {
		return InvalidParameterIn("")
	}
	return o.In
}

func (o *InvalidParameter) GetName() *string {
	if o == nil {
		return nil
	}
	return o.Name
}

func (o *InvalidParameter) GetPath() *string {
	if o == nil {
		return nil
	}
	return o.Path
}

func (o *InvalidParameter) GetTitle() string {
	if o == nil {
		return ""
	}
	return o.Title
}

func (o *InvalidParameter) GetType() string {
	if o == nil {
		return ""
	}
	return o.Type
}
