// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

import (
	"encoding/json"
	"fmt"
)

// NotFoundProblemDetailProblemDetailStatus - The HTTP status code generated by the origin server for this occurrence of the problem.
type NotFoundProblemDetailProblemDetailStatus int64

const (
	NotFoundProblemDetailProblemDetailStatusFourHundred              NotFoundProblemDetailProblemDetailStatus = 400
	NotFoundProblemDetailProblemDetailStatusFourHundredAndOne        NotFoundProblemDetailProblemDetailStatus = 401
	NotFoundProblemDetailProblemDetailStatusFourHundredAndTwo        NotFoundProblemDetailProblemDetailStatus = 402
	NotFoundProblemDetailProblemDetailStatusFourHundredAndThree      NotFoundProblemDetailProblemDetailStatus = 403
	NotFoundProblemDetailProblemDetailStatusFourHundredAndFour       NotFoundProblemDetailProblemDetailStatus = 404
	NotFoundProblemDetailProblemDetailStatusFourHundredAndNine       NotFoundProblemDetailProblemDetailStatus = 409
	NotFoundProblemDetailProblemDetailStatusFourHundredAndTwentyNine NotFoundProblemDetailProblemDetailStatus = 429
	NotFoundProblemDetailProblemDetailStatusFiveHundred              NotFoundProblemDetailProblemDetailStatus = 500
)

func (e NotFoundProblemDetailProblemDetailStatus) ToPointer() *NotFoundProblemDetailProblemDetailStatus {
	return &e
}

func (e *NotFoundProblemDetailProblemDetailStatus) UnmarshalJSON(data []byte) error {
	var v int64
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case 400:
		fallthrough
	case 401:
		fallthrough
	case 402:
		fallthrough
	case 403:
		fallthrough
	case 404:
		fallthrough
	case 409:
		fallthrough
	case 429:
		fallthrough
	case 500:
		*e = NotFoundProblemDetailProblemDetailStatus(v)
		return nil
	default:
		return fmt.Errorf("invalid value for NotFoundProblemDetailProblemDetailStatus: %v", v)
	}
}

// NotFoundProblemDetail - Represents when the server can not find the requested resource.
type NotFoundProblemDetail struct {
	// A human-readable explanation specific to this occurrence of the problem.
	Detail *string `json:"detail,omitempty"`
	// A URI reference that identifies the specific occurrence of the problem.
	Instance *string                                  `json:"instance,omitempty"`
	Status   NotFoundProblemDetailProblemDetailStatus `json:"status"`
	// A short, human-readable summary of the problem type.
	Title string `json:"title"`
	// A URI reference that identifies the problem type.
	Type string `json:"type"`
}

func (o *NotFoundProblemDetail) GetDetail() *string {
	if o == nil {
		return nil
	}
	return o.Detail
}

func (o *NotFoundProblemDetail) GetInstance() *string {
	if o == nil {
		return nil
	}
	return o.Instance
}

func (o *NotFoundProblemDetail) GetStatus() NotFoundProblemDetailProblemDetailStatus {
	if o == nil {
		return NotFoundProblemDetailProblemDetailStatus(0)
	}
	return o.Status
}

func (o *NotFoundProblemDetail) GetTitle() string {
	if o == nil {
		return ""
	}
	return o.Title
}

func (o *NotFoundProblemDetail) GetType() string {
	if o == nil {
		return ""
	}
	return o.Type
}
