// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

import (
	"encoding/json"
	"fmt"
)

// PaymentRequiredProblemDetailProblemDetailStatus - The HTTP status code generated by the origin server for this occurrence of the problem.
type PaymentRequiredProblemDetailProblemDetailStatus int64

const (
	PaymentRequiredProblemDetailProblemDetailStatusFourHundred              PaymentRequiredProblemDetailProblemDetailStatus = 400
	PaymentRequiredProblemDetailProblemDetailStatusFourHundredAndOne        PaymentRequiredProblemDetailProblemDetailStatus = 401
	PaymentRequiredProblemDetailProblemDetailStatusFourHundredAndTwo        PaymentRequiredProblemDetailProblemDetailStatus = 402
	PaymentRequiredProblemDetailProblemDetailStatusFourHundredAndThree      PaymentRequiredProblemDetailProblemDetailStatus = 403
	PaymentRequiredProblemDetailProblemDetailStatusFourHundredAndFour       PaymentRequiredProblemDetailProblemDetailStatus = 404
	PaymentRequiredProblemDetailProblemDetailStatusFourHundredAndNine       PaymentRequiredProblemDetailProblemDetailStatus = 409
	PaymentRequiredProblemDetailProblemDetailStatusFourHundredAndTwentyNine PaymentRequiredProblemDetailProblemDetailStatus = 429
	PaymentRequiredProblemDetailProblemDetailStatusFiveHundred              PaymentRequiredProblemDetailProblemDetailStatus = 500
)

func (e PaymentRequiredProblemDetailProblemDetailStatus) ToPointer() *PaymentRequiredProblemDetailProblemDetailStatus {
	return &e
}

func (e *PaymentRequiredProblemDetailProblemDetailStatus) UnmarshalJSON(data []byte) error {
	var v int64
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case 400:
		fallthrough
	case 401:
		fallthrough
	case 402:
		fallthrough
	case 403:
		fallthrough
	case 404:
		fallthrough
	case 409:
		fallthrough
	case 429:
		fallthrough
	case 500:
		*e = PaymentRequiredProblemDetailProblemDetailStatus(v)
		return nil
	default:
		return fmt.Errorf("invalid value for PaymentRequiredProblemDetailProblemDetailStatus: %v", v)
	}
}

// PaymentRequiredProblemDetail - Represents when the server is refusing access to the resource until payment has been made.
type PaymentRequiredProblemDetail struct {
	// A human-readable explanation specific to this occurrence of the problem.
	Detail *string `json:"detail,omitempty"`
	// A URI reference that identifies the specific occurrence of the problem.
	Instance *string                                         `json:"instance,omitempty"`
	Status   PaymentRequiredProblemDetailProblemDetailStatus `json:"status"`
	// A short, human-readable summary of the problem type.
	Title string `json:"title"`
	// A URI reference that identifies the problem type.
	Type string `json:"type"`
}

func (o *PaymentRequiredProblemDetail) GetDetail() *string {
	if o == nil {
		return nil
	}
	return o.Detail
}

func (o *PaymentRequiredProblemDetail) GetInstance() *string {
	if o == nil {
		return nil
	}
	return o.Instance
}

func (o *PaymentRequiredProblemDetail) GetStatus() PaymentRequiredProblemDetailProblemDetailStatus {
	if o == nil {
		return PaymentRequiredProblemDetailProblemDetailStatus(0)
	}
	return o.Status
}

func (o *PaymentRequiredProblemDetail) GetTitle() string {
	if o == nil {
		return ""
	}
	return o.Title
}

func (o *PaymentRequiredProblemDetail) GetType() string {
	if o == nil {
		return ""
	}
	return o.Type
}
